#!/usr/bin/env python3
"""Generate build/help.inc (the HELP-screen text data) from help.txt.

Source format (help.txt):
  - '#...'        comment line (ignored)
  - blank line    a blank screen row
  - '---'         page break (starts a new HELP page)
  - '@VERSION'    the live version + build stamp (drawn by the ROM, not here)
  - anything else a screen row; leading spaces kept, trailing trimmed

Emits, per page, a run of null-terminated lines ended by $FF, a word pointer
table (help_pages), str_help, and HELP_PAGES. The ROM's help_draw_row walks a
page's lines by row; a line that is just $01 is the version placeholder.

Errors (nonzero exit) if a line exceeds the Game Gear window width or a page has
too many rows -- so bad edits fail the build instead of clipping on hardware.
"""
import sys, os

SRC = sys.argv[1] if len(sys.argv) > 1 else "help.txt"
OUT = sys.argv[2] if len(sys.argv) > 2 else "build/help.inc"
MAX_W = 20        # Game Gear window is 20 columns (HELP text starts at col 0)
MAX_ROWS = 16     # grid content rows per page


def parse(path):
    pages = [[]]
    with open(path, encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n").rstrip("\r")
            if line.startswith("#"):
                continue
            line = line.rstrip()                     # trim trailing, keep leading
            if line.strip() == "---":
                pages.append([])
                continue
            pages[-1].append((lineno, line))
    # drop leading/trailing blank rows of each page; keep empty pages out
    result = []
    for pg in pages:
        while pg and pg[0][1] == "":
            pg.pop(0)
        while pg and pg[-1][1] == "":
            pg.pop()
        if pg:
            result.append(pg)
    return result


def main():
    pages = parse(SRC)
    errs = []
    if not pages:
        errs.append("no pages found")
    for pi, pg in enumerate(pages):
        if len(pg) > MAX_ROWS:
            errs.append(f"page {pi + 1}: {len(pg)} rows > {MAX_ROWS}")
        for lineno, line in pg:
            if line == "@VERSION":
                continue
            if '"' in line:
                errs.append(f"line {lineno}: contains a double-quote")
            if len(line) > MAX_W:
                errs.append(f"line {lineno}: {len(line)} chars > {MAX_W}: {line!r}")
    if errs:
        for e in errs:
            sys.stderr.write(f"makehelp: ERROR: {e}\n")
        sys.exit(1)

    os.makedirs(os.path.dirname(OUT) or ".", exist_ok=True)
    with open(OUT, "w") as o:
        o.write("; generated by tools/makehelp.py from help.txt -- do not edit\n")
        o.write(f".DEFINE HELP_PAGES {len(pages)}\n")
        o.write('.BANK 1 SLOT 1\n')
        o.write('.SECTION "HelpData" FREE\n')
        o.write('str_help: .db "HELP", 0\n')
        o.write("help_pages:\n")
        o.write("  .dw " + ", ".join(f"help_p{i}" for i in range(len(pages))) + "\n")
        for pi, pg in enumerate(pages):
            o.write(f"help_p{pi}:\n")
            for _lineno, line in pg:
                if line == "@VERSION":
                    o.write("  .db $01, 0                 ; live version + build stamp\n")
                elif line == "":
                    o.write("  .db 0\n")
                else:
                    o.write(f'  .db "{line}", 0\n')
            o.write("  .db $FF\n")
        o.write(".ENDS\n")
    sys.stderr.write(f"makehelp: {len(pages)} pages, "
                     f"{sum(len(p) for p in pages)} lines -> {OUT}\n")


if __name__ == "__main__":
    main()
