#!/usr/bin/env python3
"""Boot-splash logo: image -> deduped 1bpp tiles + tilemap.

Targets the GG window width (152 px = 19 tiles); the same data is
centred on the SMS. Emits logo.bin (map bytes, then 8-byte tiles)
and logo.inc (defines + INCBIN slices). Ink = dark pixels; the
image is flattened onto white first so transparency reads as bg.

usage: makelogo.py IN.IMG OUT.BIN OUT.INC
"""
import sys
from PIL import Image

TARGET_W = 152

def main():
    src, out_bin, out_inc = sys.argv[1:4]
    img = Image.open(src)
    if img.mode in ("RGBA", "LA", "P"):
        img = img.convert("RGBA")
        flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
        flat.alpha_composite(img)
        img = flat.convert("L")
    else:
        img = img.convert("L")

    w, h = img.size
    tw = TARGET_W
    th = round(h * tw / w)
    th8 = (th + 7) // 8 * 8
    im = img.resize((tw, th), Image.LANCZOS)
    canvas = Image.new("L", (tw, th8), 255)
    canvas.paste(im, (0, (th8 - th) // 2))
    px = canvas.load()

    tiles, tmap = {}, []
    for ty in range(th8 // 8):
        for tx in range(tw // 8):
            rows = bytes(
                sum((0x80 >> x) for x in range(8)
                    if px[tx * 8 + x, ty * 8 + y] < 128)
                for y in range(8))
            tmap.append(tiles.setdefault(rows, len(tiles)))
    assert len(tiles) <= 255, "too many unique tiles (%d)" % len(tiles)

    mw, mh = tw // 8, th8 // 8
    tile_data = b"".join(sorted(tiles, key=tiles.get))
    with open(out_bin, "wb") as f:
        f.write(bytes(tmap) + tile_data)
    with open(out_inc, "w") as f:
        f.write("; generated by tools/makelogo.py - do not edit\n"
                ".DEFINE LOGO_W %d\n.DEFINE LOGO_H %d\n"
                ".DEFINE LOGO_TILES %d\n"
                ".BANK 1 SLOT 1\n.SECTION \"Logo\" FREE\n"
                "logo_map:\n  .INCBIN \"logo.bin\" SKIP 0 READ %d\n"
                "logo_tiles:\n  .INCBIN \"logo.bin\" SKIP %d READ %d\n"
                ".ENDS\n"
                % (mw, mh, len(tiles), mw * mh, mw * mh, len(tiles) * 8))
    print("logo: %dx%d px, %dx%d map, %d tiles, ~%d bytes ROM -> %s" %
          (tw, th, mw, mh, len(tiles), len(tiles) * 8 + mw * mh, out_bin))

if __name__ == "__main__":
    main()
