#!/usr/bin/env python3
"""Generate SMSGGDJ note-period tables (WLA-DX include).

Two tables, one per region: the PSG divides the system clock, which
differs between PAL (3546893 Hz) and NTSC (3579545 Hz) machines - the
same period value sounds ~16 cents sharper on NTSC. Each table is
computed for A=440 against its own clock.

freq = clk / (32 * period)  ->  period = clk / (32 * freq), 10 bits.
Range: A2 (MIDI 45, lowest note with period <= 1023) .. B7 (MIDI 107).

Also emits 3-char note names ("A-2", "A#2", ...) so the Z80 never has
to divide by 12.
"""
import sys

CLK_PAL = 3546893
CLK_NTSC = 3579545
MIDI_LO = 45            # A2 (index 0 -- do NOT lower this; it would shift every
                        #     saved note index. Extend only the top.)
MIDI_HI = 155           # B11 -- as high as the SN76489 goes (period ~2); useful
                        #     for pitched noise. Octaves 10/11 wrap in the display.
MIDI_WRAP = 132         # C10: first note whose octave is 2 digits; the editor
                        #     shows these with a trailing '+' and a single digit.
NAMES = ["C-", "C#", "D-", "D#", "E-", "F-",
         "F#", "G-", "G#", "A-", "A#", "B-"]


def notename(m):        # 3 chars; octave wraps mod 10 (10->0, 11->1) past B9
    return NAMES[m % 12] + str((m // 12 - 1) % 10)


def period(clk, midi):
    f = 440.0 * 2.0 ** ((midi - 69) / 12.0)
    return max(1, min(1023, round(clk / (32.0 * f))))


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: maketables.py OUT.INC")
    notes = range(MIDI_LO, MIDI_HI + 1)
    lines = []
    lines.append("; generated by tools/maketables.py - do not edit")
    lines.append(".DEFINE NOTE_COUNT %d" % len(notes))
    lines.append(".DEFINE NOTE_WRAP %d" % (MIDI_WRAP - MIDI_LO))  # index of first 2-digit octave
    lines.append('.SECTION "NoteTables" FREE')
    for label, clk in (("note_table_pal", CLK_PAL),
                       ("note_table_ntsc", CLK_NTSC)):
        lines.append("%s:" % label)
        for m in notes:
            name = NAMES[m % 12] + str(m // 12 - 1)
            lines.append("  .dw %4d  ; %s" % (period(clk, m), name))
    lines.append("note_names:")
    for m in notes:
        name = NAMES[m % 12] + str(m // 12 - 1)
        lines.append('  .db "%s"' % notename(m))

    # LFO tables: 16 depths x 32-step triangle, precomputed so the
    # Z80 never multiplies. vib = signed period delta (+-depth),
    # trem = unsigned volume dip (0..depth).
    def tri(i):
        ph = (i % 32) / 32.0
        if ph < 0.25:
            return ph * 4
        if ph < 0.75:
            return 2 - ph * 4
        return ph * 4 - 4

    # exponential depth curve: fine at the bottom, wild at the top
    # (+-60 period units ~= +-4 semitones around A-4)
    VIB_AMP = [0, 1, 2, 3, 4, 5, 6, 8, 10, 13, 17, 22, 28, 36, 46, 60]
    lines.append("vib_tables:")
    for depth in range(16):
        amp = VIB_AMP[depth]
        row = [round(amp * tri(i)) & 0xFF for i in range(32)]
        lines.append("  .db " + ", ".join("$%02X" % v for v in row))
    lines.append("trem_tables:")
    for depth in range(16):
        row = [round(depth * (1 - tri((i + 8) % 32)) / 2) for i in range(32)]
        lines.append("  .db " + ", ".join("$%02X" % v for v in row))

    # wavetable pitch: phase increment per feed tick (8.8 fixed),
    # f = feed * inc / (256 * 32)  ->  inc = f * 8192 / feed
    for label, feed in (("winc_table_pal", 15625 / 2.0),
                        ("winc_table_ntsc", 15734.25 / 2.0)):
        lines.append("%s:" % label)
        for m in notes:
            f = 440.0 * 2.0 ** ((m - 69) / 12.0)
            inc = min(65535, round(f * 8192.0 / feed))
            lines.append("  .dw %5d  ; %s" % (inc, NAMES[m % 12] + str(m // 12 - 1)))

    # YM2413 FM note table (SMS FM unit). F-number (9-bit) + block
    # (octave), block chosen so fnum lands in [256,511] for the most
    # precision. Per note, 2 bytes: byte 0 = fnum low 8 ($10-reg);
    # byte 1 = block<<1 | fnum-bit8 (the $20-reg pitch bits; the engine
    # ORs in key-on / sustain at trigger). Fsam = clock / 72.
    #
    # FM is voiced FM_OCT_SHIFT octaves BELOW the PSG note of the same index:
    # index 0 (shown "A-2") starts low, and walking the note field up (into the
    # '+' wrap octaves) reaches the whole FM range directly from the pitch field
    # -- no per-instrument octave setting. The note NAME is PSG-referenced, so an
    # FM instrument sounds FM_OCT_SHIFT octaves below its label.
    FM_OCT_SHIFT = 2
    for label, clk in (("fm_note_pal", CLK_PAL), ("fm_note_ntsc", CLK_NTSC)):
        lines.append("%s:" % label)
        fsam = clk / 72.0
        for m in notes:
            f = 440.0 * 2.0 ** ((m - 12 * FM_OCT_SHIFT - 69) / 12.0)
            for block in range(8):
                fnum = round(f * 524288.0 / (fsam * (2.0 ** block)))
                if fnum <= 511:
                    break
            fnum = max(0, min(511, fnum))
            b1 = (block << 1) | ((fnum >> 8) & 1)
            lines.append("  .db $%02X, $%02X  ; %s"
                         % (fnum & 0xFF, b1, NAMES[m % 12] + str(m // 12 - 1)))

    # preset waveforms: 32 steps, stored as ready-to-OUT bytes
    # ($D0 | attenuation, attenuation = 15 - drawn value).
    # First four are the boot defaults; all eight stamp via the
    # WAVE screen's preset cycler.
    import math as _m
    def wavebytes(vals):
        return ", ".join("$%02X" % (0xD0 | (15 - v)) for v in vals)
    sine = [round((_m.sin(2 * _m.pi * i / 32) * 0.5 + 0.5) * 15) for i in range(32)]
    trit = [round(tri((i + 8) % 32) * 7.5 + 7.5) for i in range(32)]
    saw = [round(i * 15 / 31.0) for i in range(32)]
    sqr = [15] * 16 + [0] * 16
    p25 = [15] * 8 + [0] * 24
    p12 = [15] * 4 + [0] * 28
    org = []
    for i in range(32):
        th = 2 * _m.pi * i / 32
        v = _m.sin(th) + _m.sin(3 * th) / 3 + _m.sin(5 * th) / 5
        org.append(round((v / 1.4 * 0.5 + 0.5) * 15))
    org = [max(0, min(15, v)) for v in org]
    rseed = 0xACE1
    rnd = []
    for i in range(32):
        rseed = (rseed * 0x6255 + 0x3217) & 0xFFFF
        rnd.append(rseed >> 12)
    lines.append("default_waves:")
    for w in (sine, trit, saw, sqr, p25, p12, org, rnd):
        lines.append("  .db " + wavebytes(w))
    lines.append(".ENDS")
    with open(sys.argv[1], "w") as f:
        f.write("\n".join(lines) + "\n")
    print("note tables: %d notes (%s..%s) -> %s" % (
        len(notes), NAMES[MIDI_LO % 12] + str(MIDI_LO // 12 - 1),
        NAMES[MIDI_HI % 12] + str(MIDI_HI // 12 - 1), sys.argv[1]))


if __name__ == "__main__":
    main()
