#!/usr/bin/env python3
"""Generate SMSDJ note-period tables (WLA-DX include).

Two tables, one per region: the PSG divides the system clock, which
differs between PAL (3546893 Hz) and NTSC (3579545 Hz) machines - the
same period value sounds ~16 cents sharper on NTSC. Each table is
computed for A=440 against its own clock.

freq = clk / (32 * period)  ->  period = clk / (32 * freq), 10 bits.
Range: A2 (MIDI 45, lowest note with period <= 1023) .. B7 (MIDI 107).

Also emits 3-char note names ("A-2", "A#2", ...) so the Z80 never has
to divide by 12.
"""
import sys

CLK_PAL = 3546893
CLK_NTSC = 3579545
MIDI_LO = 45            # A2
MIDI_HI = 107           # B7
NAMES = ["C-", "C#", "D-", "D#", "E-", "F-",
         "F#", "G-", "G#", "A-", "A#", "B-"]


def period(clk, midi):
    f = 440.0 * 2.0 ** ((midi - 69) / 12.0)
    return max(1, min(1023, round(clk / (32.0 * f))))


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: maketables.py OUT.INC")
    notes = range(MIDI_LO, MIDI_HI + 1)
    lines = []
    lines.append("; generated by tools/maketables.py - do not edit")
    lines.append(".DEFINE NOTE_COUNT %d" % len(notes))
    lines.append('.SECTION "NoteTables" FREE')
    for label, clk in (("note_table_pal", CLK_PAL),
                       ("note_table_ntsc", CLK_NTSC)):
        lines.append("%s:" % label)
        for m in notes:
            name = NAMES[m % 12] + str(m // 12 - 1)
            lines.append("  .dw %4d  ; %s" % (period(clk, m), name))
    lines.append("note_names:")
    for m in notes:
        name = NAMES[m % 12] + str(m // 12 - 1)
        lines.append('  .db "%s"' % name)

    # LFO tables: 16 depths x 32-step triangle, precomputed so the
    # Z80 never multiplies. vib = signed period delta (+-depth),
    # trem = unsigned volume dip (0..depth).
    def tri(i):
        ph = (i % 32) / 32.0
        if ph < 0.25:
            return ph * 4
        if ph < 0.75:
            return 2 - ph * 4
        return ph * 4 - 4

    # exponential depth curve: fine at the bottom, wild at the top
    # (+-60 period units ~= +-4 semitones around A-4)
    VIB_AMP = [0, 1, 2, 3, 4, 5, 6, 8, 10, 13, 17, 22, 28, 36, 46, 60]
    lines.append("vib_tables:")
    for depth in range(16):
        amp = VIB_AMP[depth]
        row = [round(amp * tri(i)) & 0xFF for i in range(32)]
        lines.append("  .db " + ", ".join("$%02X" % v for v in row))
    lines.append("trem_tables:")
    for depth in range(16):
        row = [round(depth * (1 - tri((i + 8) % 32)) / 2) for i in range(32)]
        lines.append("  .db " + ", ".join("$%02X" % v for v in row))
    lines.append(".ENDS")
    with open(sys.argv[1], "w") as f:
        f.write("\n".join(lines) + "\n")
    print("note tables: %d notes (%s..%s) -> %s" % (
        len(notes), NAMES[MIDI_LO % 12] + str(MIDI_LO // 12 - 1),
        NAMES[MIDI_HI % 12] + str(MIDI_HI // 12 - 1), sys.argv[1]))


if __name__ == "__main__":
    main()
