#!/usr/bin/env python3
"""SMSDJ sample converter (design doc 10.5).

Converts WAV files into the SMSDJ 4-bit PCM pool. The SN76489's
volume register is a LOGARITHMIC DAC (2 dB per step, datasheet):
level n outputs amplitude 10^(-n/10), level 15 is 0. Linear PCM is
mapped to the nearest log level with 1-D error-diffusion dithering —
the correction step almost no commercial SMS game bothered with.

usage:
  smsdj_sample.py in1.wav [in2.wav ...] -o pool.bin [options]
    --asm pool.inc    WLA-DX include with the pool index
    --rate HZ         target rate (default 7813 = PAL line/2 cadence)
    --gate N          silence-gate threshold, levels (default 1)
    --gain X          post-normalize gain with hard clipping
                      (2-4 = louder/denser, 99 ~= 1-bit loudness)
    --no-dither       plain nearest-level quantization
    --no-norm         skip per-file normalization
    --preview         write NAME.preview.wav rendered through the
                      exact level table (what the console will play)
"""
import math
import struct
import sys
import wave

# unipolar DAC levels: attenuation 0..14 = 10^(-n/10), 15 = off
LEVELS = [10 ** (-n / 10.0) for n in range(15)] + [0.0]


def load_wav(path):
    w = wave.open(path, "rb")
    ch, width, rate, n = (w.getnchannels(), w.getsampwidth(),
                          w.getframerate(), w.getnframes())
    raw = w.readframes(n)
    w.close()
    if width == 2:
        data = struct.unpack("<%dh" % (n * ch), raw)
        scale = 32768.0
    elif width == 1:
        data = [b - 128 for b in raw]
        scale = 128.0
    else:
        sys.exit("%s: only 8/16-bit WAV supported" % path)
    # mix to mono
    mono = [sum(data[i * ch:(i + 1) * ch]) / (ch * scale)
            for i in range(n)]
    return mono, rate


def resample(samples, src, dst):
    if src == dst or not samples:
        return samples
    out, step = [], src / float(dst)
    pos, last = 0.0, len(samples) - 1
    while pos < last:
        i = int(pos)
        f = pos - i
        out.append(samples[i] * (1 - f) + samples[i + 1] * f)
        pos += step
    return out


def convert(samples, dither=True, gate=1):
    """signed [-1,1] -> 4-bit attenuation codes, log-mapped."""
    out, err = [], 0.0
    for s in samples:
        u = (s + 1.0) / 2.0          # unipolar DC range
        if dither:
            u += err
        best = min(range(16), key=lambda n: abs(LEVELS[n] - u))
        if dither:
            err = u - LEVELS[best]
            err = max(-0.5, min(0.5, err))
        out.append(best)
    if gate:
        # mute sub-noise-floor passages (mid-level wobble)
        mid = 7
        for i, v in enumerate(out):
            if abs(LEVELS[v] - 0.5) < (LEVELS[mid] - LEVELS[mid + gate]):
                out[i] = mid
    return out


def main():
    args = sys.argv[1:]
    if not args or "-o" not in args:
        sys.exit(__doc__)

    def opt(flag, default=None, has_val=True):
        if flag in args:
            i = args.index(flag)
            args.pop(i)
            return args.pop(i) if has_val else True
        return default

    out_bin = opt("-o")
    out_asm = opt("--asm")
    rate = int(opt("--rate", 7813))
    gain = float(opt("--gain", 1.0))
    gate = int(opt("--gate", 1))
    dither = not opt("--no-dither", False, has_val=False)
    norm = not opt("--no-norm", False, has_val=False)
    preview = opt("--preview", False, has_val=False)

    pool, index = bytearray(), []
    for path in args:
        mono, src = load_wav(path)
        mono = resample(mono, src, rate)
        if norm and mono:
            peak = max(0.0001, max(abs(s) for s in mono))
            mono = [s / peak for s in mono]
        if gain != 1.0:
            mono = [max(-1.0, min(1.0, s * gain)) for s in mono]
        codes = convert(mono, dither, gate)
        if len(codes) & 1:
            codes.append(15)
        packed = bytes((codes[i] << 4) | codes[i + 1]
                       for i in range(0, len(codes), 2))
        name = path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
        index.append((name, len(pool), len(packed)))
        pool += packed
        secs = len(codes) / float(rate)
        print("%-12s %6d bytes  %.2fs" % (name, len(packed), secs))
        if preview:
            pv = wave.open(name + ".preview.wav", "wb")
            pv.setnchannels(1)
            pv.setsampwidth(1)
            pv.setframerate(rate)
            pv.writeframes(bytes(
                int(LEVELS[c] * 255) for c in codes))
            pv.close()

    open(out_bin, "wb").write(pool)
    print("pool: %d bytes (%.1f%% of a 16K bank) -> %s" %
          (len(pool), 100.0 * len(pool) / 16384, out_bin))

    if out_asm:
        lines = ["; generated by tools/smsdj_sample.py - do not edit",
                 ".DEFINE SAMPLE_COUNT %d" % len(index),
                 ".DEFINE SAMPLE_RATE %d" % rate,
                 "sample_table:"]
        for name, off, ln in index:
            lines.append("  .dw $%04X, $%04X  ; %s" % (off, ln, name))
        open(out_asm, "w").write("\n".join(lines) + "\n")
        print("index -> " + out_asm)


if __name__ == "__main__":
    main()
